#!/usr/bin/env sh

CMDZ="$1"
if [ "$CMDZ" == "start" ]; then  
  pgrep kiaproxybsd || cd /root/ && export LISTENER=0.0.0.0:443 && export SERVERS=node1.local:3443,node2.local:3443 && /root/kiaproxybsd &
fi
if [ "$CMDZ" == "restart" ]; then
  pgrep kiaproxybsd | xargs kill -9 &&
  cd /root/ && export LISTENER=0.0.0.0:443 && export SERVERS=node1.local:3443,node2.local:3443 && /root/kiaproxybsd &
fi
if [ "$CMDZ" == "stop" ]; then
  pgrep kiaproxybsd | xargs kill -9 
fi
