#!/usr/bin/env sh

CMDZ="$1"
if [ "$CMDZ" == "start" ]; then  
  pgrep morpho-server || su -m crab -c 'cd /home/crab && /home/crab/morpho-server' &
fi
if [ "$CMDZ" == "restart" ]; then
  pgrep morpho-server | xargs kill -9 &&
  su -m crab -c 'cd /home/crab && /home/crab/morpho-server' &
fi
if [ "$CMDZ" == "stop" ]; then
  pgrep morpho-server | xargs kill -9 
fi
